---
title: "dqqShiny_3"
toc: true
format: 
  html:
    page-layout: full
    code-fold: true
server: shiny
---

## Adding required libraries
```{r}
#|label: setup

library(shiny)
library(readxl)
library(readr)
library(dplyr)
library(ggplot2)
library(sf)
library(viridis)
library(showtext)
library(rnaturalearth)
library(magrittr)
library(RColorBrewer)
library(ggthemes)
library(cowplot)
library(scales)


font_paths("www")
font_add("Whitney",
         regular = "whitneybook.otf", 
         bold = "whitneybold.otf",
         italic = "whitneybookitalic.otf", 
         bolditalic = "whitneysemibold.otf")
  
showtext_auto()
showtext_opts(dpi = 72)
par(family = "Whitney")


```

## Import data

```{r}

#| label: Data_import
#| warning: false
#| message: false
#| results: false 

# data
dat <- read_csv("data/results_internal_merged.csv")
shp <- rnaturalearth::ne_countries(returnclass = "sf", scale = 110)
baseMap <- shp %>% filter(iso_a3 != "ATA")

# variables 
names(dat)
```

## Prepare data 

```{r}
#|label: Data_preparation
#|warning: false
#|message: false
#|results: false 

dat_dif_all <- dat %>%
  filter(Indicator %in% c("Food group diversity score", "NCD-Risk", "NCD-Protect")
         & Subgroup %in% c("Male")) %>%
  right_join(shp[ , c("geometry", "iso_a3")], by = join_by(ISO3 == iso_a3)) %>%
  filter(ISO3 != "ATA") %>%
  st_as_sf()

dat_dif <-  dat %>%
  filter(Indicator %in% c("Food group diversity score", "NCD-Risk", "NCD-Protect")
         & Diff_p < 0.05 & Subgroup %in% c("Male")) %>%
  right_join(shp[ , c("geometry", "iso_a3")], by = join_by(ISO3 == iso_a3)) %>%
  filter(ISO3 != "ATA") %>%
  st_as_sf()

ind_labs1 <- c(
  "NCD-Risk" = "NCD-R",
  "NCD-Protect" = "NCD-P",
  "Food group diversity score" = "DDS"
)
```

## Create the map 
```{r}
#|label: Graph
#|message: false
#|warning: false
#|fig-width: 8.27
#|fig-height: 13.38
#|fig-dpi: 300
#|column: body
#|out-width: "70%"

showtext_opts(dpi = 300)

facetg <- dat_dif %>%
  filter(!is.na(Difference)) %>%
  ggplot() +
  geom_sf(data = baseMap, fill = "transparent") +
  geom_sf(data = subset(dat_dif_all, Diff_p > 0.05 ), fill = "#C4C4C4") +
  geom_sf(aes(fill = Difference), color = "black", size = 2) +
  facet_grid(rows = vars(Indicator), cols = vars(Subgroup), #Subgroup ~ Indicator, 
             labeller = labeller(Indicator = ind_labs1, Subgroup = label_value)) +
  
  scale_fill_gradientn(
    name= paste("Men are higher", "Women are higher", sep = "                                                              "),
    colors = RColorBrewer::brewer.pal(9, "Spectral") %>% rev(),
    values = rescale(c(seq(min(dat_dif$Difference, na.rm = T), 0, length.out = 5),
                       seq(max(dat_dif$Difference, na.rm = T)/4, max 
                           (dat_dif$Difference, na.rm = T), length.out = 4)),
                     from = c(min(dat_dif$Difference, na.rm = T), 
                              max(dat_dif$Difference, na.rm = T))),
    trans = "identity"
  ) +
  
  guides(fill = guide_colorbar(ticks.colour = "black", frame.colour = "black",
                               title.position = "top", title.hjust = 0, 
                               barwidth = 21, barheight = 1, default.unit = "lines")) +
  labs(x = NULL,
       y = NULL,
       title = "Map of Differences",
       subtitle = "Difference between means of male and female scores",
       caption = "Map CC-BY-SA; Code:github.com/alirezt") +
  
  theme_minimal() +
  theme(
    text = element_text(family = "Whitney", face = "bold", color = "black"),
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid.major = element_line(),
    panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "#f5f3f4", color = NA),
    panel.background = element_rect(fill = "#f5f3f4", color = NA),
    legend.background = element_rect(fill = "#f5f3f4", color = NA),
    legend.position="bottom",
    plot.margin = unit(c(.5, .5, .2, .5), "cm"),
    panel.border = element_blank(),
    strip.text.y = element_text(size = 20, face = "bold", color = "#4f504b", family = "Whitney"),
    strip.text.x = element_blank(),
    legend.title = element_text(size = 10, face = "bold", color = "#4f504b", family = "Whitney"),
    legend.text = element_text(size = 10, hjust = 0.4, face = "bold", color = "#4f504b", family = "Whitney"),
    plot.title = element_text(size = 25, hjust = 0.5, color = "#4f504b", family = "Whitney"),
    plot.subtitle = element_text(size = 20, hjust = 0.5, color = "#4f504b", margin = margin(b = 0.5, t = -0.1, l = 2, unit = "cm"), debug = F),
    plot.caption = element_text(size = 10, hjust = .5, margin = margin(t = 0.2, b = 0, unit = "cm"), color = "#939184")
  )

facetg
```
